### ISSUE TITLE
missing fonts

### ISSUE THREAD

**Issue by VictorDrijkoningen** [adityapattiyeri/home-remote#3]
Hi!

Can i request that you put your fonts in the repo?

cheers

**Comment by adityapattiyeri** [comment]
I am not sure how they are licensed. You can find the links to all the fonts below, just be sure to edit the file name in the code.

Material design: [https://github.com/Templarian/MaterialDesign-Webfont/blob/master/fonts/materialdesignicons-webfont.ttf](url)

Tahoma regular: [https://www.dafontfree.net/tahoma-regular/f102825.htm](url)

BebasNeue regular: [https://github.com/dharmatype/Bebas-Neue/blob/master/fonts/BebasNeue(2018)ByDhamraType/ttf/BebasNeue-Regular.ttf](url)
