### ISSUE TITLE
Auto Sleep

### ISSUE THREAD

**Issue by gazelle-hub** [adityapattiyeri/home-remote#5]
Hi there,

This is a bit of a noob question, but I was looking through the code and I can see how the auto_sleep script is started but I can't figure out how it starts again if another button is pushed? 

Thanks in advance for your help.

**Comment by gazelle-hub** [comment]
Sorry, I've just figured this one out.

You've got "mode: restart" in the script so every time it is executed it restarts the counter.

**Comment by adityapattiyeri** [comment]
Hey,

 Yes. The script restarts and resets the counter every time the button is pressed.
